default_language_version:
    # force all unspecified python hooks to run python3
    python: python3

exclude: ^tests/
#types: [python]
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.1.0
      hooks:
          - id: check-ast
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-json
          - id: check-merge-conflict
          - id: check-yaml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-vcs-permalinks
          - id: flake8
            types: [python]
            additional_dependencies:
            - flake8-bugbear==18.8.0
            - flake8-builtins==1.4.1
            - flake8-comprehensions==1.4.1
            - flake8-per-file-ignores==0.6
            - flake8-tidy-imports==1.1.0
            - flake8==3.5.0
            - pycodestyle<2.4.0,>=2.0.0
    - repo: https://github.com/asottile/pyupgrade
      rev: v1.14.0
      hooks:
        - id: pyupgrade
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.700
      hooks:
        - id: mypy
          exclude: ^lyft_forecasting/seasonality/kalman_filter.py
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
      - id: black
        types: [python]
        language_version: python3
